import cv2
import numpy as np
from hsv_pipeline import hsv_filter

class BallDetector:
    def __init__(self, lower_hsv=(20, 20, 20), upper_hsv=(255, 255, 225), blur_size=5,
                 erode_size=0, dilate_size=0, morph_operation_type="OPENING",
                 contour_mode="EXTERNAL_ONLY", draw_contours=True,
                 min_area=100, max_area=50000, min_circularity=0.3,
                 roi_normalized=(1, 1, 200, 200)): # roi_normalized = (x_min_norm, y_min_norm, x_max_norm, y_max_norm)
        """
        Initializes the BallDetector with HSV bounds and blob detection parameters.

        Args:
            lower_hsv (tuple): Lower HSV threshold (H, S, V).
            upper_hsv (tuple): Upper HSV threshold (H, S, V).
            blur_size (int): Size of the Gaussian blur kernel. Must be an odd number.
            erode_size (int): Size of the erosion kernel. 0 to disable.
            dilate_size (int): Size of the dilation kernel. 0 to disable.
            morph_operation_type (str): "OPENING" (erode then dilate) or "CLOSING" (dilate then erode).
            contour_mode (str): "EXTERNAL_ONLY" or "ALL_FLATTENED_HIERARCHY".
            draw_contours (bool): Whether to draw contours on the output frame.
            min_area (int): Minimum contour area to consider as a blob.
            max_area (int): Maximum contour area to consider as a blob.
            min_circularity (float): Minimum circularity to consider as a blob.
            roi_normalized (tuple, optional): Normalized ROI (x_min, y_min, x_max, y_max) where values are 0-1.
                                              If None, the entire frame is processed.
        """
        self.lower_hsv = lower_hsv
        self.upper_hsv = upper_hsv
        self.blur_size = blur_size if blur_size % 2 == 1 else blur_size + 1 # Ensure odd blur size
        self.erode_size = erode_size
        self.dilate_size = dilate_size
        self.morph_operation_type = morph_operation_type
        self.draw_contours = draw_contours
        self.min_area = min_area
        self.max_area = max_area
        self.min_circularity = min_circularity
        self.roi_normalized = roi_normalized

        if contour_mode == "EXTERNAL_ONLY":
            self.contour_mode = cv2.RETR_EXTERNAL
        elif contour_mode == "ALL_FLATTENED_HIERARCHY":
            self.contour_mode = cv2.RETR_LIST
        else:
            raise ValueError("Invalid contour mode. Use 'EXTERNAL_ONLY' or 'ALL_FLATTENED_HIERARCHY'.")

    def process_frame(self, frame):
        """
        Processes a single frame to detect balls.

        Args:
            frame (numpy.ndarray): The input image frame in BGR format.

        Returns:
            numpy.ndarray: The frame with detected balls circled.
            list: A list of (center_x, center_y, radius) for detected blobs.
            numpy.ndarray: The mask generated by HSV filtering.
        """
        frame_height, frame_width = frame.shape[:2]
        display_frame = frame.copy()

        # Apply ROI if specified
        if self.roi_normalized:
            x_min_norm, y_min_norm, x_max_norm, y_max_norm = self.roi_normalized
            x_min = int(x_min_norm * frame_width)
            y_min = int(y_min_norm * frame_height)
            x_max = int(x_max_norm * frame_width)
            y_max = int(y_max_norm * frame_height)

            # Ensure ROI coordinates are within frame bounds
            x_min = max(0, x_min)
            y_min = max(0, y_min)
            x_max = min(frame_width, x_max)
            y_max = min(frame_height, y_max)

            roi_frame = frame[y_min:y_max, x_min:x_max]
            if roi_frame.size == 0: # Handle empty ROI
                empty_mask = np.zeros((frame_height, frame_width), dtype=np.uint8)
                empty_filtered_image = np.zeros_like(frame)
                return display_frame, [], empty_mask, empty_filtered_image, empty_mask, empty_mask
        else:
            roi_frame = frame
            x_min, y_min = 0, 0

        # Apply Gaussian blur to smooth the image
        if self.blur_size > 0:
            blurred_frame = cv2.GaussianBlur(roi_frame, (self.blur_size, self.blur_size), 0)
        else:
            blurred_frame = roi_frame.copy()

        # Apply HSV filter
        filtered_image, current_mask = hsv_filter(blurred_frame, self.lower_hsv, self.upper_hsv)

        eroded_mask_display = np.zeros_like(current_mask)
        dilated_mask_display = np.zeros_like(current_mask)

        # Apply morphological operations
        if self.erode_size > 0:
            erode_element = cv2.getStructuringElement(cv2.MORPH_RECT, (self.erode_size, self.erode_size))
        else:
            erode_element = None

        if self.dilate_size > 0:
            dilate_element = cv2.getStructuringElement(cv2.MORPH_RECT, (self.dilate_size, self.dilate_size))
        else:
            dilate_element = None

        if self.morph_operation_type == "OPENING":
            if erode_element is not None:
                current_mask = cv2.erode(current_mask, erode_element)
                eroded_mask_display = current_mask.copy() # Capture eroded state
            if dilate_element is not None:
                current_mask = cv2.dilate(current_mask, dilate_element)
                dilated_mask_display = current_mask.copy() # Capture dilated state
        elif self.morph_operation_type == "CLOSING":
            if dilate_element is not None:
                current_mask = cv2.dilate(current_mask, dilate_element)
                dilated_mask_display = current_mask.copy() # Capture dilated state
            if erode_element is not None:
                current_mask = cv2.erode(current_mask, erode_element)
                eroded_mask_display = current_mask.copy() # Capture eroded state

        # Find contours
        contours, _ = cv2.findContours(current_mask, self.contour_mode, cv2.CHAIN_APPROX_SIMPLE)

        detected_blobs = []

        for contour in contours:
            # Shift contour points back to original frame coordinates
            shifted_contour = contour + (x_min, y_min)

            # Approximate contour to a polygon
            epsilon = 0.04 * cv2.arcLength(shifted_contour, True)
            approx = cv2.approxPolyDP(shifted_contour, epsilon, True)

            # Calculate area and circularity
            area = cv2.contourArea(shifted_contour)
            if not (self.min_area <= area <= self.max_area):
                continue

            # Fit a circle to the contour
            (x, y), radius = cv2.minEnclosingCircle(approx)
            center = (int(x), int(y))
            radius = int(radius)

            # Filter by circularity
            perimeter = cv2.arcLength(shifted_contour, True)
            if perimeter == 0:
                continue
            circularity = 4 * np.pi * area / (perimeter ** 2)
            if circularity < self.min_circularity:
                continue

            # Draw the circle
            if self.draw_contours:
                cv2.circle(display_frame, center, radius, (0, 255, 0), 2) # Green circle
            detected_blobs.append((center[0], center[1], radius))

        # Draw ROI rectangle on the display frame if specified
        if self.roi_normalized:
            cv2.rectangle(display_frame, (x_min, y_min), (x_max, y_max), (255, 0, 0), 2) # Blue ROI rectangle

        # Create full-size masks for display, if ROI was used
        full_mask = np.zeros((frame_height, frame_width), dtype=np.uint8)
        full_filtered_image = np.zeros_like(frame)
        full_eroded_mask_display = np.zeros((frame_height, frame_width), dtype=np.uint8)
        full_dilated_mask_display = np.zeros((frame_height, frame_width), dtype=np.uint8)

        if self.roi_normalized:
            full_mask[y_min:y_max, x_min:x_max] = current_mask
            full_filtered_image[y_min:y_max, x_min:x_max] = filtered_image
            full_eroded_mask_display[y_min:y_max, x_min:x_max] = eroded_mask_display
            full_dilated_mask_display[y_min:y_max, x_min:x_max] = dilated_mask_display
        else:
            full_mask = current_mask
            full_filtered_image = filtered_image
            full_eroded_mask_display = eroded_mask_display
            full_dilated_mask_display = dilated_mask_display

        return display_frame, detected_blobs, full_mask, full_filtered_image, full_eroded_mask_display, full_dilated_mask_display

if __name__ == '__main__':
    # Example usage with a dummy image
    dummy_image = np.zeros((400, 600, 3), dtype=np.uint8)
    # Draw a green circle (within the specified HSV range)
    cv2.circle(dummy_image, (300, 200), 50, (60, 150, 100), -1) # Example green-ish color in BGR

    detector = BallDetector()
    processed_frame, keypoints, mask = detector.process_frame(dummy_image)

    cv2.imshow("Original Image", dummy_image)
    cv2.imshow("Processed Frame with Blobs", processed_frame)
    cv2.imshow("Mask", mask)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    # Example usage with camera (uncomment to test)
    # cap = cv2.VideoCapture(0)
    # if not cap.isOpened():
    #     print("Error: Could not open camera.")
    # else:
    #     while True:
    #         ret, frame = cap.read()
    #         if not ret:
    #             break
    #         processed_frame, keypoints, mask = detector.process_frame(frame)
    #         cv2.imshow("Camera Feed with Blobs", processed_frame)
    #         cv2.imshow("Mask", mask)
    #         if cv2.waitKey(1) & 0xFF == ord('q'):
    #             break
    #     cap.release()
    #     cv2.destroyAllWindows()
